### ISSUE TITLE
Optimize backup/recovery flow

### ISSUE THREAD

**Issue by vb7401** [project-vinyl/jubmoji.quest#5]
Cleared out this issue in favor of other ones.

**Comment by AndrewCLu** [comment]
Can also encrypt backups with a password

**Comment by vb7401** [comment]
Yep, we should include support for this. Zupass team has an implementation that we can build off of as its all GPL-3 licensed

**Comment by vb7401** [comment]
@AndrewCLu Feel free to break this issue up into more issues, and to rearrange the other recovery related issues

**Comment by AndrewCLu** [comment]
Breaking this down into the 3 main recovery issues: compressing backups, adding a WhatsApp recovery flow, and a server-side backup flow.
